version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    versioning-strategy: lockfile-only

  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
